swagger: "2.0"

info:
  version: 0.1.0
  title: Transit API
  description: UI for stops, routes, trip plans and everything in-between
  license:
    name: Mozilla Public License Version 2.0
    url: https://www.mozilla.org/en-US/MPL/2.0/
  contact:
    name: OpenTransitTools
    url: http://opentransittools.com/api
    email: api@opentransittools.com

schemes:
  - https
host: opentransittools.com
basePath: /transit

paths:
  /stop_image:
    get:
      summary: return a map image of a stop
      description: Returns a png or jpeg catrographic map image, with a stop specified as the center point
      parameters:
       - name: stop_id
         in: query
         description: GTFS stop_id
         type: string
         required: true
       - name: type
         in: query
         description: png for a carto map image (with a return path of .png) or jpeg for a ortho image
         type: string
      responses:
        200:
          description: A map image
          headers:
            Content-Type:
              description: image/png, image/jpeg
              type: image
          schema:
            type: file
